### ISSUE TITLE
Runtime ImportModuleErrror for DeployFunction Lambda

### ISSUE THREAD

**Issue by dvesh23** [awslabs/aws-streaming-media-analytics#29]
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1029:21)",
        "    at async start (file:///var/runtime/index.mjs:1192:23)",
        "    at async file:///var/runtime/index.mjs:1198:1"
    ]
}

**Comment by alcousins** [comment]
Looking. It would be helpful to know exactly where this error came from. Will do a test deploy soon as likely something has changed in lambda runtime as versions have been updated. We might need to package the sdk as part of the build.

**Comment by dvesh23** [comment]
This error came from deploying the stack in CFN when DeployFunction Resource failed to create 


```
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [331f939e-51dd-45eb-ab34-f2442936a6ac]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

```

**Comment by velartur** [comment]
[aws-streaming-analyticsv2.yaml.zip](https://github.com/awslabs/aws-streaming-media-analytics/files/12324127/aws-streaming-analyticsv2.yaml.zip)

Uploading fixed CloudFormation Template. BR

**Comment by alcousins** [comment]
Thanks arturo; a diff shows the key change is the Runtime version in deployment.yaml. 

Working on testing a build with this updated.

**Comment by alcousins** [comment]
I have merged an update for this now. I still need to rebuild the deployment artifacts in the documentation. Working on this.
